version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sbx-tsql
    restart: always
    environment:
      SA_PASSWORD: ${ROOT_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
