version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sbx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: experiments
      MYSQL_USER: sbx-user
      MYSQL_PASSWORD: ${USR_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
